<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Test\Browse\Enums;

use Enbit\eBaySDK\Browse\Enums\AvailabilityThresholdEnum;

class AvailabilityThresholdEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new AvailabilityThresholdEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Browse\Enums\AvailabilityThresholdEnum', $this->obj);
    }
}
