<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Test\Catalog\Enums;

use Enbit\eBaySDK\Catalog\Enums\ChangeRequestStatus;

class ChangeRequestStatusTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new ChangeRequestStatus();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Catalog\Enums\ChangeRequestStatus', $this->obj);
    }
}
