<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Merchandising\Services;

class MerchandisingService extends \Enbit\eBaySDK\Merchandising\Services\MerchandisingBaseService
{
    const API_VERSION = '1.5.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getRelatedCategoryItems(\Enbit\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request)
    {
        return $this->getRelatedCategoryItemsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRelatedCategoryItemsAsync(\Enbit\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getRelatedCategoryItems',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getMostWatchedItems(\Enbit\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request)
    {
        return $this->getMostWatchedItemsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMostWatchedItemsAsync(\Enbit\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getMostWatchedItems',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse
     */
    public function getTopSellingProducts(\Enbit\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request)
    {
        return $this->getTopSellingProductsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTopSellingProductsAsync(\Enbit\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request)
    {
        return $this->callOperationAsync(
            'getTopSellingProducts',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetDealsRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getDeals(\Enbit\eBaySDK\Merchandising\Types\GetDealsRequest $request)
    {
        return $this->getDealsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetDealsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDealsAsync(\Enbit\eBaySDK\Merchandising\Types\GetDealsRequest $request)
    {
        return $this->callOperationAsync(
            'getDeals',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getSimilarItems(\Enbit\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request)
    {
        return $this->getSimilarItemsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSimilarItemsAsync(\Enbit\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getSimilarItems',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetVersionRequest $request
     * @return \Enbit\eBaySDK\Merchandising\Types\GetVersionResponse
     */
    public function getVersion(\Enbit\eBaySDK\Merchandising\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Merchandising\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\Enbit\eBaySDK\Merchandising\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\Enbit\eBaySDK\Merchandising\Types\GetVersionResponse'
        );
    }
}
