<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Shopping\Services;

class ShoppingService extends \Enbit\eBaySDK\Shopping\Services\ShoppingBaseService
{
    const API_VERSION = '1027';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\FindProductsRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\FindProductsResponseType
     */
    public function findProducts(\Enbit\eBaySDK\Shopping\Types\FindProductsRequestType $request)
    {
        return $this->findProductsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\FindProductsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsAsync(\Enbit\eBaySDK\Shopping\Types\FindProductsRequestType $request)
    {
        return $this->callOperationAsync(
            'FindProducts',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\FindProductsResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetCategoryInfoResponseType
     */
    public function getCategoryInfo(\Enbit\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request)
    {
        return $this->getCategoryInfoAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCategoryInfoAsync(\Enbit\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request)
    {
        return $this->callOperationAsync(
            'GetCategoryInfo',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetCategoryInfoResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetItemStatusRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetItemStatusResponseType
     */
    public function getItemStatus(\Enbit\eBaySDK\Shopping\Types\GetItemStatusRequestType $request)
    {
        return $this->getItemStatusAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetItemStatusRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getItemStatusAsync(\Enbit\eBaySDK\Shopping\Types\GetItemStatusRequestType $request)
    {
        return $this->callOperationAsync(
            'GetItemStatus',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetItemStatusResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetMultipleItemsResponseType
     */
    public function getMultipleItems(\Enbit\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request)
    {
        return $this->getMultipleItemsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMultipleItemsAsync(\Enbit\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request)
    {
        return $this->callOperationAsync(
            'GetMultipleItems',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetMultipleItemsResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetShippingCostsResponseType
     */
    public function getShippingCosts(\Enbit\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request)
    {
        return $this->getShippingCostsAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShippingCostsAsync(\Enbit\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request)
    {
        return $this->callOperationAsync(
            'GetShippingCosts',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetShippingCostsResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetSingleItemRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetSingleItemResponseType
     */
    public function getSingleItem(\Enbit\eBaySDK\Shopping\Types\GetSingleItemRequestType $request)
    {
        return $this->getSingleItemAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetSingleItemRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSingleItemAsync(\Enbit\eBaySDK\Shopping\Types\GetSingleItemRequestType $request)
    {
        return $this->callOperationAsync(
            'GetSingleItem',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetSingleItemResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetUserProfileRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GetUserProfileResponseType
     */
    public function getUserProfile(\Enbit\eBaySDK\Shopping\Types\GetUserProfileRequestType $request)
    {
        return $this->getUserProfileAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GetUserProfileRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserProfileAsync(\Enbit\eBaySDK\Shopping\Types\GetUserProfileRequestType $request)
    {
        return $this->callOperationAsync(
            'GetUserProfile',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GetUserProfileResponseType'
        );
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request
     * @return \Enbit\eBaySDK\Shopping\Types\GeteBayTimeResponseType
     */
    public function geteBayTime(\Enbit\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request)
    {
        return $this->geteBayTimeAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geteBayTimeAsync(\Enbit\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request)
    {
        return $this->callOperationAsync(
            'GeteBayTime',
            $request,
            '\Enbit\eBaySDK\Shopping\Types\GeteBayTimeResponseType'
        );
    }
}
