language: php

php:
  - 7.4
  - 8.0snapshot

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

install:
  - 'echo "xdebug.mode = profile" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source

script:
  - make test
