<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\BusinessPoliciesManagement\Services;

class BusinessPoliciesManagementService extends \Enbit\eBaySDK\BusinessPoliciesManagement\Services\BusinessPoliciesManagementBaseService
{
    const API_VERSION = '1.0.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionResponse
     */
    public function getVersion(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetVersionResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileResponse
     */
    public function removeProfile(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileRequest $request)
    {
        return $this->removeProfileAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeProfileAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileRequest $request)
    {
        return $this->callOperationAsync(
            'removeProfile',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveProfileResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileResponse
     */
    public function addSellerProfile(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileRequest $request)
    {
        return $this->addSellerProfileAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addSellerProfileAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileRequest $request)
    {
        return $this->callOperationAsync(
            'addSellerProfile',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\AddSellerProfileResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesResponse
     */
    public function getSellerProfiles(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesRequest $request)
    {
        return $this->getSellerProfilesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSellerProfilesAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesRequest $request)
    {
        return $this->callOperationAsync(
            'getSellerProfiles',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetSellerProfilesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileResponse
     */
    public function setSellerProfile(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileRequest $request)
    {
        return $this->setSellerProfileAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setSellerProfileAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileRequest $request)
    {
        return $this->callOperationAsync(
            'setSellerProfile',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\SetSellerProfileResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesResponse
     */
    public function removeSellerProfiles(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesRequest $request)
    {
        return $this->removeSellerProfilesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeSellerProfilesAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesRequest $request)
    {
        return $this->callOperationAsync(
            'removeSellerProfiles',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveSellerProfilesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesResponse
     */
    public function consolidateShippingProfiles(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesRequest $request)
    {
        return $this->consolidateShippingProfilesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function consolidateShippingProfilesAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesRequest $request)
    {
        return $this->callOperationAsync(
            'consolidateShippingProfiles',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\ConsolidateShippingProfilesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusResponse
     */
    public function getConsolidationJobStatus(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusRequest $request)
    {
        return $this->getConsolidationJobStatusAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsolidationJobStatusAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusRequest $request)
    {
        return $this->callOperationAsync(
            'getConsolidationJobStatus',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\GetConsolidationJobStatusResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesRequest $request
     * @return \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesResponse
     */
    public function removeOverrides(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesRequest $request)
    {
        return $this->removeOverridesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeOverridesAsync(\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesRequest $request)
    {
        return $this->callOperationAsync(
            'removeOverrides',
            $request,
            '\Enbit\eBaySDK\BusinessPoliciesManagement\Types\RemoveOverridesResponse'
        );
    }
}
