<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Test\Marketing\Types;

use Enbit\eBaySDK\Marketing\Types\FindCampaignByAdReferenceRestResponse;

class FindCampaignByAdReferenceRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new FindCampaignByAdReferenceRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Marketing\Types\FindCampaignByAdReferenceRestResponse', $this->obj);
    }

    public function testExtendsCampaigns()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Marketing\Types\Campaigns', $this->obj);
    }
}
