<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Test\Inventory\Types;

use Enbit\eBaySDK\Inventory\Types\GetProductCompatibilityRestResponse;

class GetProductCompatibilityRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetProductCompatibilityRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Inventory\Types\GetProductCompatibilityRestResponse', $this->obj);
    }

    public function testExtendsCompatibility()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Inventory\Types\Compatibility', $this->obj);
    }
}
