<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\Test\Fulfillment\Enums;

use Enbit\eBaySDK\Fulfillment\Enums\LineItemFulfillmentStatusEnum;

class LineItemFulfillmentStatusEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new LineItemFulfillmentStatusEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\Enbit\eBaySDK\Fulfillment\Enums\LineItemFulfillmentStatusEnum', $this->obj);
    }
}
