<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Enbit\eBaySDK\ProductMetadata\Services;

class ProductMetadataService extends \Enbit\eBaySDK\ProductMetadata\Services\ProductMetadataBaseService
{
    const API_VERSION = '1.3.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesResponse
     */
    public function getProductSearchNames(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request)
    {
        return $this->getProductSearchNamesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchNamesAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchNames',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchNamesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesResponse
     */
    public function getCompatibilitySearchNames(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request)
    {
        return $this->getCompatibilitySearchNamesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchNamesAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchNames',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse
     */
    public function getProductSearchValues(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request)
    {
        return $this->getProductSearchValuesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchValuesAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchValues',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse
     */
    public function getProductSearchValuesBulk(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request)
    {
        return $this->getProductSearchValuesBulkAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchValuesBulkAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchValuesBulk',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesResponse
     */
    public function getCompatibilitySearchValues(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request)
    {
        return $this->getCompatibilitySearchValuesAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchValuesAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchValues',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse
     */
    public function getCompatibilitySearchValuesBulk(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request)
    {
        return $this->getCompatibilitySearchValuesBulkAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchValuesBulkAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchValuesBulk',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionResponse
     */
    public function getProductSearchDataVersion(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request)
    {
        return $this->getProductSearchDataVersionAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchDataVersionAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchDataVersion',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionResponse
     */
    public function getCompatibilitySearchDataVersion(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request)
    {
        return $this->getCompatibilitySearchDataVersionAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchDataVersionAsync(\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchDataVersion',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionResponse'
        );
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request
     * @return \Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkResponse
     */
    public function getProductMetadataBulk(\Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request)
    {
        return $this->getProductMetadataBulkAsync($request)->wait();
    }

    /**
     * @param \Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductMetadataBulkAsync(\Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getProductMetadataBulk',
            $request,
            '\Enbit\eBaySDK\ProductMetadata\Types\ProductMetadataBulkResponse'
        );
    }
}
